# Public package exports for the Autonomic Python SDK.
from __future__ import annotations

from .amplifier import MirageAmplifier
from .amplifier_codec import (
    AMPLIFIER_DIAGNOSTIC_PORT,
    ALL_OUTPUTS,
    decode_output_address,
    encode_output_address,
)
from .amplifier_types import (
    AmplifierDeviceInfo,
    AmplifierDeviceLinkInfo,
    AmplifierDeviceStateInfo,
    AmplifierDeviceSubInfo,
    AmplifierDiscovery,
    AmplifierInputGain,
    AmplifierLayout,
    AmplifierNetworkInfo,
    AmplifierOutputName,
    AmplifierPresetGroup,
    AmplifierPresetGroupMap,
    AmplifierResponse,
    AmplifierResetDefaults,
    AmplifierRemoteSource,
    AmplifierSourceDetails,
    AmplifierSourceMetadata,
    AmplifierSourceDelay,
    AmplifierSourceName,
    AmplifierZoneGroup,
)
from .connection import LineConnection
from .exceptions import (
    AutonomicError,
    AutonomicTimeoutError,
    CommandError,
    ConnectionClosedError,
    NotConnectedError,
    ProtocolError,
)
from .client import DEFAULT_HOST, DEFAULT_SOURCE_ALIASES, AutonomicClient
from .config import (
    AutonomicConfig,
    DirectAmplifierConfig,
    DirectLocalSourceConfig,
    DirectRemoteSourceConfig,
    load_config,
)
from .hardware import HARDWARE_MODELS, HardwareModel, model_for_byte, model_name_for_byte
from .models import (
    AutonomicOutput,
    AutonomicOutputGroup,
    AutonomicPartyModeInfo,
    AutonomicSource,
    AutonomicZoneGroup,
)
from .protocol_types import (
    BrowseItem,
    BrowseResponse,
    CommandResponse,
    Event,
    StatusSnapshot,
)
from .mrad import MirageAudioSystem
from .mrad_types import MRAD_PORT, MRADCommandHelp, MRADVersion
from .protocol import format_assignment, format_command, parse_event, parse_xml_list

__all__ = [
    "AMPLIFIER_DIAGNOSTIC_PORT",
    "ALL_OUTPUTS",
    "AmplifierDeviceInfo",
    "AmplifierDeviceLinkInfo",
    "AmplifierDeviceStateInfo",
    "AmplifierDeviceSubInfo",
    "AmplifierDiscovery",
    "AmplifierInputGain",
    "AmplifierLayout",
    "AmplifierNetworkInfo",
    "AmplifierOutputName",
    "AmplifierPresetGroup",
    "AmplifierPresetGroupMap",
    "AmplifierResponse",
    "AmplifierResetDefaults",
    "AmplifierRemoteSource",
    "AmplifierSourceDetails",
    "AmplifierSourceMetadata",
    "AmplifierSourceDelay",
    "AmplifierSourceName",
    "AmplifierZoneGroup",
    "AutonomicClient",
    "AutonomicConfig",
    "AutonomicError",
    "AutonomicTimeoutError",
    "AutonomicOutput",
    "AutonomicOutputGroup",
    "AutonomicPartyModeInfo",
    "AutonomicSource",
    "AutonomicZoneGroup",
    "BrowseItem",
    "BrowseResponse",
    "CommandError",
    "CommandResponse",
    "ConnectionClosedError",
    "DEFAULT_HOST",
    "DEFAULT_SOURCE_ALIASES",
    "DirectAmplifierConfig",
    "DirectLocalSourceConfig",
    "DirectRemoteSourceConfig",
    "Event",
    "HARDWARE_MODELS",
    "HardwareModel",
    "LineConnection",
    "MRAD_PORT",
    "MRADCommandHelp",
    "MRADVersion",
    "MirageAmplifier",
    "MirageAudioSystem",
    "NotConnectedError",
    "ProtocolError",
    "StatusSnapshot",
    "decode_output_address",
    "encode_output_address",
    "format_assignment",
    "format_command",
    "load_config",
    "model_for_byte",
    "model_name_for_byte",
    "parse_event",
    "parse_xml_list",
]
